apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: rihabbennour/mavenbuild
          imagePullPolicy: Always 
          ports:
            - containerPort: 8083 
            
            
            
 ---
 
 
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  label:
    app: my-app
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - nodeport: 30036
    port: 80 
    targetPort: 8083
