apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  label:
    app: my-app
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - nodeport: 30036
    port: 80 
    targetPort: 8083
  
